name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: image build from dockerfile
      run: |
        echo "FROM CentOS
              RUN dnf install httpd && \
              systemctl enable httpd
              WORKDIR /var/www/html
              CMD pwd
              COPY app.html index.html
              CMD ["httpd", "-D", "FOREGROUND"]" > Dockerfile
        cd /docker
        docker build -t himangshu12/test_1:ciapp /docker
  image-push: 
    need: docker 
    run-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
            run:
              docker push himangshu12/test_1:ciapp
