name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: image build from dockerfile
        run: docker build -t himangshu12/test_1:ciapp-${GITHUB_RUN_NUMBER} .
      - name: image-push 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push himangshu12/test_1:ciapp-${GITHUB_RUN_NUMBER}
