name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: image build from dockerfile
        run: |
          echo "FROM CentOS
                RUN dnf install httpd -y && \
                systemctl enable httpd
                WORKDIR /var/www/html
                CMD pwd
                COPY app.html index.html
                CMD [\"httpd\", \"-D\", \"FOREGROUND\"]" > Dockerfile
          cd /docker
          docker build -t himangshu12/test_1:ciapp /docker

  image-push: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push himangshu12/test_1:ciapp
